### PR TITLE
clean up before a new release

### PR DESCRIPTION
**Pull request by witokondoria**
removing old files and bumping stratio parent

### CODE REVIEW

**Comment by darroyocazorla** [comment]
:shipit:

**Comment by darroyocazorla** [comment]
:shipit:

**Comment by stratiocommit** [comment]
A job will handle this PR ASAP on [Jenkins](http://jenkins.stratio.com/job/SparkLibs/job/SparkMongo/320/)

**Comment by stratiocommit** [comment]
Rebase && testing in progress

**Pull request merged**
