### PR TITLE
Overwrite value when current key is existing

### PR DESCRIPTION
**Pull request by giaosudau**
If you have set up this in MongodbConfigBuilder
UpdateFields -> Array("widgetId", "interactionId", "section", "date", "publisher", "os", "device", "browser")))

and when you have data have those keys it will do update into that collection without make new record if current key is existing.

### CODE REVIEW

**Comment by compae** [comment]
This PR make the same operation than the last implementation over MongoDB documents. But if the user have documents with more fields than the dataFrame, the old code replace and the new add fields.

Good Job, I merge this PR.

**Comment by compae** [comment]
Make another PR with the correct License.

**Comment by cperezmig** [comment]
This change is already merged or just revert due to problems in the commit? May I help?

**Comment by giaosudau** [comment]
@cperezmig This one already merged.
Check that https://github.com/Stratio/Spark-MongoDB/commit/65a656d31e513f2ed19745b645c23e434fa15a0f

**Comment by DeeeFOX** [comment]
Could you show an example in python code?

**Pull request merged**
